apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fronted-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fronted-deployment
  template:
    metadata:
      labels:
        app: fronted-deployment
    spec:
      containers:
        - name: frontend-container
          image: frenzy669/tomerkrexam:frontend
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: fronted-lb 
spec:
  type: LoadBalancer
  selector:
    app: fronted-deployment 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002