apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: my-backend-container 
          image: frenzy669/tomerkrexam:backend
          ports:
            - containerPort: 5001 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service 
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5001
